# app/prompts/prompt_loader.py
"""
מודול לייבוא כל הפרומפטים מ-system_prompts.py
משמש כנקודת גישה מרכזית לכל הפרומפטים במערכת
"""

import json

from .system_prompts import (
    create_project_plan_promt,
    _ai_optimize_task_schedule_prompt,
    process_and_generate_step_content_promt,
    _check_for_duplicate_task_promt,
    generate_analytical_roadmap_promt,
    autonomously_advance_mission_planning_prompt,
    _operate_on_tic_promt,
    consolidate_mission_log_if_needed_promt,
    update_tic_from_side_chat_endpoint_promt,
    draft_message_universal_promt,
    draft_message_universal_drafting_promt,
    handle_communication_request_find_person,
    handle_communication_request_promt_personal,
    handle_communication_request_promt_group,
    generate_daily_briefing_promt,
    generate_end_of_day_report_promt,
    find_quick_answer_online_promt,
    find_quick_answer_online_synthesizer_promt,
    perform_advanced_research_promt,
    perform_advanced_research_synthesizer_promt,
    execute_search_multi_task_prompt,
    execute_search_multi_task_synthesizer_promt,
    extract_text_from_file_vision_prompt,
    analyze_document_and_update_tic_promt,
    generate_semantic_filename_promt,
    visualize_data_promt,
    generate_presentation_feature_promt,
    execute_task_main_promt,
    generate_and_build_flow_promt,
    initialize_bot_persona_promt,
    set_goal_promt,
)

__all__ = [
    "create_project_plan_promt",
    "_ai_optimize_task_schedule_prompt",
    "process_and_generate_step_content_promt",
    "_check_for_duplicate_task_promt",
    "generate_analytical_roadmap_promt",
    "autonomously_advance_mission_planning_prompt",
    "_operate_on_tic_promt",
    "consolidate_mission_log_if_needed_promt",
    "update_tic_from_side_chat_endpoint_promt",
    "draft_message_universal_promt",
    "draft_message_universal_drafting_promt",
    "handle_communication_request_find_person",
    "handle_communication_request_promt_personal",
    "handle_communication_request_promt_group",
    "generate_daily_briefing_promt",
    "generate_end_of_day_report_promt",
    "find_quick_answer_online_promt",
    "find_quick_answer_online_synthesizer_promt",
    "perform_advanced_research_promt",
    "perform_advanced_research_synthesizer_promt",
    "execute_search_multi_task_prompt",
    "execute_search_multi_task_synthesizer_promt",
    "extract_text_from_file_vision_prompt",
    "analyze_document_and_update_tic_promt",
    "generate_semantic_filename_promt",
    "visualize_data_promt",
    "generate_presentation_feature_promt",
    "execute_task_main_promt",
    "generate_and_build_flow_promt",
    "initialize_bot_persona_promt",
    "set_goal_promt",
    "json",
]
